In [2]:
import numpy as np
import pandas as pd

def upgma(matrix, labels):
    # Initialisation
    n = len(matrix)
    clusters = {i: [labels[i]] for i in range(n)}
    distances = matrix.copy()

    # Convertir en DataFrame pour une gestion facile des distances
    df_distances = pd.DataFrame(distances, index=range(n), columns=range(n))

    while len(clusters) > 1:
        # Trouver les deux clusters les plus proches
        min_dist = np.inf
        to_merge = (None, None)
        for i in df_distances.index:
            for j in df_distances.columns:
                if i != j and df_distances.at[i, j] < min_dist:
                    min_dist = df_distances.at[i, j]
                    to_merge = (i, j)

        # Fusionner les deux clusters
        i, j = to_merge
        new_cluster = clusters[i] + clusters[j]
        clusters[i] = new_cluster
        del clusters[j]

        # Mettre à jour la matrice des distances
        for k in df_distances.index:
            if k != i and k in df_distances.columns:
                dist_i = df_distances.at[i, k]
                dist_j = df_distances.at[j, k]
                df_distances.at[i, k] = df_distances.at[k, i] = (dist_i + dist_j) / 2

        # Supprimer la colonne et la ligne du cluster fusionné
        df_distances = df_distances.drop(index=j, columns=j)

    # Obtenir le cluster final
    return list(clusters.values())

# Exemple de matrice de distances et labels
labels = ['Bsu', 'Bst', 'Lvi', 'Amo', 'Mlu']
data = [
    [0, 0.1715, 0.2147, 0.3091, 0.2326],
    [0.1715, 0, 0.2991, 0.3399, 0.2058],
    [0.2147, 0.2991, 0, 0.2795, 0.3943],
    [0.3091, 0.3399, 0.2795, 0, 0.4289],
    [0.2326, 0.2058, 0.3943, 0.4289, 0]
]

matrix = np.array(data)

# Test de l'algorithme UPGMA
resultat = upgma(matrix, labels)
print("Résultat de l'UPGMA:", resultat)


Résultat de l'UPGMA: [['Bsu', 'Bst', 'Mlu', 'Lvi', 'Amo']]


In [3]:
import numpy as np
import pandas as pd

def upgma(matrix, labels):
    # Initialisation
    n = len(matrix)
    clusters = {i: [labels[i]] for i in range(n)}
    distances = matrix.copy()

    # Convertir en DataFrame pour une gestion facile des distances
    df_distances = pd.DataFrame(distances, index=range(n), columns=range(n))
    history = []  # Liste pour sauvegarder les distances de chaque étape

    while len(clusters) > 1:
        # Trouver les deux clusters les plus proches
        min_dist = np.inf
        to_merge = (None, None)
        for i in df_distances.index:
            for j in df_distances.columns:
                if i != j and df_distances.at[i, j] < min_dist:
                    min_dist = df_distances.at[i, j]
                    to_merge = (i, j)

        # Sauvegarder les distances des clusters avant fusion
        history.append({
            'merged_clusters': (to_merge[0], to_merge[1]),
            'distances': df_distances.copy()
        })

        # Fusionner les deux clusters
        i, j = to_merge
        new_cluster = clusters[i] + clusters[j]
        clusters[i] = new_cluster
        del clusters[j]

        # Mettre à jour la matrice des distances
        for k in df_distances.index:
            if k != i and k in df_distances.columns:
                dist_i = df_distances.at[i, k]
                dist_j = df_distances.at[j, k]
                df_distances.at[i, k] = df_distances.at[k, i] = (dist_i + dist_j) / 2

        # Supprimer la colonne et la ligne du cluster fusionné
        df_distances = df_distances.drop(index=j, columns=j)

    # Sauvegarder les distances finales
    history.append({
        'merged_clusters': None,
        'distances': df_distances
    })

    # Obtenir le cluster final
    return list(clusters.values()), history

# Exemple de matrice de distances et labels
labels = ['Bsu', 'Bst', 'Lvi', 'Amo', 'Mlu']
data = [
    [0, 0.1715, 0.2147, 0.3091, 0.2326],
    [0.1715, 0, 0.2991, 0.3399, 0.2058],
    [0.2147, 0.2991, 0, 0.2795, 0.3943],
    [0.3091, 0.3399, 0.2795, 0, 0.4289],
    [0.2326, 0.2058, 0.3943, 0.4289, 0]
]

matrix = np.array(data)

# Test de l'algorithme UPGMA
resultat, historique_distances = upgma(matrix, labels)

# Afficher le résultat final
print("Résultat de l'UPGMA:", resultat)

# Afficher l'historique des distances
for step in historique_distances:
    print(f"Étape de fusion : {step['merged_clusters']}")
    print("Distances :")
    print(step['distances'])
    print()


Résultat de l'UPGMA: [['Bsu', 'Bst', 'Mlu', 'Lvi', 'Amo']]
Étape de fusion : (0, 1)
Distances :
        0       1       2       3       4
0  0.0000  0.1715  0.2147  0.3091  0.2326
1  0.1715  0.0000  0.2991  0.3399  0.2058
2  0.2147  0.2991  0.0000  0.2795  0.3943
3  0.3091  0.3399  0.2795  0.0000  0.4289
4  0.2326  0.2058  0.3943  0.4289  0.0000

Étape de fusion : (0, 4)
Distances :
        0       2       3       4
0  0.0000  0.2569  0.3245  0.2192
2  0.2569  0.0000  0.2795  0.3943
3  0.3245  0.2795  0.0000  0.4289
4  0.2192  0.3943  0.4289  0.0000

Étape de fusion : (2, 3)
Distances :
        0       2       3
0  0.0000  0.3256  0.3767
2  0.3256  0.0000  0.2795
3  0.3767  0.2795  0.0000

Étape de fusion : (0, 2)
Distances :
         0        2
0  0.00000  0.35115
2  0.35115  0.00000

Étape de fusion : None
Distances :
     0
0  0.0



In [2]:
import numpy as np
import pandas as pd


In [3]:
def search_min(matrix, col_name=None):
    print(type(matrix.columns[0]))
    print("matrix.columns ", matrix.columns)
    print("col_name ", col_name)
    print(matrix)

    if col_name != None:
        val_min = matrix[col_name].min()
        print(val_min)
        return val_min, (matrix[matrix[col_name]==val_min].index.to_list()[0], col_name)
    else:
        val_min = matrix.min(skipna=True).min()
        print(val_min)
        return val_min, matrix.stack().idxmin()

In [18]:
def search_min_ligne(matrix, line_name=None):
    print(type(matrix.index[0]))
    print("matrix.index ", matrix.index)
    print("col_name ", line_name)
    print(matrix)

    if line_name != None:
        val_min = matrix.loc[line_name].min()
        print("line_name rempli ", val_min)
        col_name = matrix.loc[line_name][matrix.loc[line_name] == val_min].index[0] if val_min in matrix.loc[line_name].values else None
        print(line_name, col_name, val_min)
        return val_min, (line_name, col_name)
    else:
        val_min = matrix.min(skipna=True).min()
        print("line_name None ",val_min)
        return val_min, matrix.stack().idxmin()

In [11]:
def search_min_ligne_index(matrix, line_name=None):
    print(type(matrix.index[0]))
    print("matrix.index ", matrix.index)
    print("col_name ", line_name)
    print(matrix)

    if line_name != None:
        val_min = matrix.loc[line_name].min()
        print("line_name rempli ", val_min)
        col_name = matrix.loc[line_name][matrix.loc[line_name] == val_min].index[0] if val_min in matrix.loc[line_name].values else None
        print(line_name, col_name, val_min)
        return val_min, (line_name, col_name)
    else:
        val_min = matrix.min(skipna=True).min()
        print("line_name None ",val_min)
        return val_min, matrix.stack().idxmin()

In [23]:
matrix2 = pd.read_csv("../matrice_test.csv", index_col=0)
matrix2 = matrix2.transpose()

print(matrix2.idxmin())

# dist_min, row_col = search_min(matrix2, "(Bst, Bsu)")
# dist_min, row_col = search_min_ligne(matrix2, "(Bst, Bsu)")

Lvi           (Bst, Bsu)
Amo           (Bst, Bsu)
Mlu           (Bst, Bsu)
(Bst, Bsu)           NaN
dtype: object


/tmp/ipykernel_3244/1891891540.py:4: FutureWarning: The behavior of DataFrame.idxmin with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  print(matrix2.idxmin())


In [5]:
def fusion_seq(matrix, dict_dist):
    # dist_min, row_col = search_min(matrix)
    dict_dist[row_col] = dist_min

In [26]:
print(type(matrix.columns))
print(matrix.columns[1])
print(matrix.columns.get_loc("Amo"))

<class 'pandas.core.indexes.base.Index'>
Amo
1


In [117]:
def calc_dist(matrix, row_col, dict_dist):
    name_col_matrix = matrix.columns
    new_dist_list = []

    row, col = row_col

    print(len(matrix))
    print((matrix.shape))
    print("MATRIX debut ------------- \n ",matrix, "\n MATRIX debut------------- \n")
    for i in name_col_matrix: 
        if i not in row_col:
            print("col-i ", col, i)
            print("row-i ", row, i)
            # print("matrix.loc[row, i] [i, row] ",matrix.loc[row, i], matrix.loc[i, row])
            # print("matrix.loc[col, i] [i, col] ",matrix.loc[col, i], matrix.loc[i, col])
            print(name_col_matrix.get_loc(i), name_col_matrix.get_loc(col), name_col_matrix.get_loc(row))
            
            nb_groupe = str(row_col).split(',')
            if name_col_matrix.get_loc(i) > name_col_matrix.get_loc(row):
                dist1 = matrix.loc[i, row]
            else:
                dist1 = matrix.loc[row, i]
            
            if name_col_matrix.get_loc(i) > name_col_matrix.get_loc(col):
                dist2 = (matrix.loc[i, col]*(len(nb_groupe)-1))
            else:
                dist2 = (matrix.loc[col, i]*(len(nb_groupe)-1))

            distance = (dist1 + dist2) / len(nb_groupe)
            new_dist_list.append(distance)
            print("new_dist_list ", new_dist_list)
            print("\n")

    if len(name_col_matrix) < 2:
        dict_dist[new_row_col] = search_min_ligne(matrix)

    matrix = matrix.drop(index=[row, col])
    matrix = matrix.drop(columns=[col, row])
    
    new_row_col = ', '.join(row_col)
    print("new_row_col ",new_row_col)
    print("new_dist_list ", new_dist_list)
    if len(name_col_matrix) > 2:
        print("len matrix sup 2")
        matrix.loc[new_row_col] = new_dist_list # avec loc : lignes
        matrix[new_row_col] = [np.nan] * len(matrix) # sans loc : colonnes
    # else:
    #     print("len matrix inf 2")
    #     dict_dist[new_row_col] = search_min_ligne(matrix)
        
    # matrix = matrix.drop(index=[row, col])
    # matrix = matrix.drop(columns=[col, row])
        
    print("MATRIX FIN------------- \n ",matrix, "\n MATRIX FIN------------- \n")
    return new_row_col, matrix

In [7]:
matrix = pd.read_csv("../matrice_dist_UPGMA.csv", index_col=0)
print(len(matrix))

print(matrix)
print("\n")
print(matrix.transpose())

5
     Bsu     Bst     Lvi     Amo     Mlu
Bsu  NaN  0.1715  0.2147  0.3091  0.2326
Bst  NaN     NaN  0.2991  0.3399  0.2058
Lvi  NaN     NaN     NaN  0.2795  0.3943
Amo  NaN     NaN     NaN     NaN  0.4289
Mlu  NaN     NaN     NaN     NaN     NaN


        Bsu     Bst     Lvi     Amo  Mlu
Bsu     NaN     NaN     NaN     NaN  NaN
Bst  0.1715     NaN     NaN     NaN  NaN
Lvi  0.2147  0.2991     NaN     NaN  NaN
Amo  0.3091  0.3399  0.2795     NaN  NaN
Mlu  0.2326  0.2058  0.3943  0.4289  NaN


In [119]:
matrix = pd.read_csv("../matrice_dist_UPGMA.csv", index_col=0)
print(len(matrix))

matrix = matrix.transpose()

dist_min, row_col = search_min_ligne(matrix)

dict_dist = dict()
dict_dist[row_col] = dist_min
print(dict_dist)

new_target, matrix = calc_dist(matrix, row_col, dict_dist)

print("len matrix ", len(matrix))
while len(matrix) > 1:
    print("len matrix debut", len(matrix))
    print("new_target ", new_target)
    dist_min, row_col = search_min_ligne(matrix, new_target)
    dict_dist[row_col] = dist_min
    new_target, matrix = calc_dist(matrix, row_col, dict_dist)
    
    print("len matrix fin", len(matrix))

print(dict_dist)
print(matrix)
# alterne entre transposer et normal ... : pq ? 

# cond de fin mauvais ? 

5
<class 'str'>
matrix.index  Index(['Bsu', 'Bst', 'Lvi', 'Amo', 'Mlu'], dtype='object')
col_name  None
        Bsu     Bst     Lvi     Amo  Mlu
Bsu     NaN     NaN     NaN     NaN  NaN
Bst  0.1715     NaN     NaN     NaN  NaN
Lvi  0.2147  0.2991     NaN     NaN  NaN
Amo  0.3091  0.3399  0.2795     NaN  NaN
Mlu  0.2326  0.2058  0.3943  0.4289  NaN
line_name None  0.1715
{('Bst', 'Bsu'): 0.1715}
5
(5, 5)
MATRIX debut ------------- 
          Bsu     Bst     Lvi     Amo  Mlu
Bsu     NaN     NaN     NaN     NaN  NaN
Bst  0.1715     NaN     NaN     NaN  NaN
Lvi  0.2147  0.2991     NaN     NaN  NaN
Amo  0.3091  0.3399  0.2795     NaN  NaN
Mlu  0.2326  0.2058  0.3943  0.4289  NaN 
 MATRIX debut------------- 

col-i  Bsu Lvi
row-i  Bst Lvi
2 0 1
new_dist_list  [0.2569]


col-i  Bsu Amo
row-i  Bst Amo
3 0 1
new_dist_list  [0.2569, 0.3245]


col-i  Bsu Mlu
row-i  Bst Mlu
4 0 1
new_dist_list  [0.2569, 0.3245, 0.2192]


new_row_col  Bst, Bsu
new_dist_list  [0.2569, 0.3245, 0.2192]
len matrix sup 

In [111]:
matrix2 = pd.read_csv("../matrice_test.csv", index_col=0)

dist_min, row_col = search_min(matrix2, "(Bst, Bsu)")

dict_dist = dict()
fusion_seq(matrix2, dict_dist)
print(dict_dist)

calc_dist(matrix2, row_col)

            Lvi     Amo     Mlu  (Bst, Bsu)
Lvi         NaN  0.2795  0.3943      0.2569
Amo         NaN     NaN  0.4289      0.3245
Mlu         NaN     NaN     NaN      0.2192
(Bst, Bsu)  NaN     NaN     NaN         NaN
{('Mlu', '(Bst, Bsu)'): 0.2192}
col-i  (Bst, Bsu) Lvi
row-i  Mlu Lvi
matrix.loc[row, i] [i, row]  nan 0.3943
matrix.loc[col, i] [i, col]  nan 0.2569


col-i  (Bst, Bsu) Amo
row-i  Mlu Amo
matrix.loc[row, i] [i, row]  nan 0.4289
matrix.loc[col, i] [i, col]  nan 0.3245


                       Lvi     Amo  ('Mlu', '(Bst, Bsu)')
Lvi                    NaN  0.2795                    NaN
Amo                    NaN     NaN                    NaN
('Mlu', '(Bst, Bsu)')  NaN     NaN                    NaN


"('Mlu', '(Bst, Bsu)')"

In [112]:
matrix = pd.read_csv("../matrice_dist_UPGMA.csv", index_col=0)

dist_min, row_col = search_min(matrix)

dict_dist = dict()
fusion_seq(matrix, dict_dist)
print(dict_dist)

calc_dist(matrix, row_col)

     Bsu     Bst     Lvi     Amo     Mlu
Bsu  NaN  0.1715  0.2147  0.3091  0.2326
Bst  NaN     NaN  0.2991  0.3399  0.2058
Lvi  NaN     NaN     NaN  0.2795  0.3943
Amo  NaN     NaN     NaN     NaN  0.4289
Mlu  NaN     NaN     NaN     NaN     NaN
{('Bsu', 'Bst'): 0.1715}
col-i  Bst Lvi
row-i  Bsu Lvi
matrix.loc[row, i] [i, row]  0.2147 nan
matrix.loc[col, i] [i, col]  0.2991 nan


col-i  Bst Amo
row-i  Bsu Amo
matrix.loc[row, i] [i, row]  0.3091 nan
matrix.loc[col, i] [i, col]  0.3399 nan


col-i  Bst Mlu
row-i  Bsu Mlu
matrix.loc[row, i] [i, row]  0.2326 nan
matrix.loc[col, i] [i, col]  0.2058 nan


                Lvi     Amo     Mlu  ('Bsu', 'Bst')
Lvi             NaN  0.2795  0.3943          0.2569
Amo             NaN     NaN  0.4289          0.3245
Mlu             NaN     NaN     NaN          0.2192
('Bsu', 'Bst')  NaN     NaN     NaN             NaN


"('Bsu', 'Bst')"

In [3]:
match_score = 1.0
mismatch_score = -1.0
gap_score = -1.0

seq1 = "GCATGCG" #en ligne X
seq2 = "GATTACA" #en colonne Y

seq1 + seq2
init la première ligne et col = avec val de gap succesive
i = deplacement en col (en x)
j = deplacement en ligne (en y)

Mij = max entre (Mi-1,j-1 + score de match ou mismatch) // (Mi-1,j + score de gap) // (Mi,j-1 + score de gap)

Avoir le chemin et score de l'alignement : 
partir de la case finale et remonter à la case max + récup nom ligne et col

In [4]:
matrix_NW = np.zeros((len(seq2)+1, len(seq1)+1))
matrix_NW

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
# init la première ligne et col = avec val de gap succesive
nb_row, nb_col = matrix_NW.shape
for i in range(1,nb_row):
    matrix_NW[0,i] = matrix_NW[0,i-1] + gap_score

for j in range(1,nb_col):
    matrix_NW[j, 0] = matrix_NW[j-1, 0] + gap_score
    
matrix_NW

array([[ 0., -1., -2., -3., -4., -5., -6., -7.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [154]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
nb_row, nb_col = array_2d.shape
print(array_2d)

for i in range(nb_row):
    for j in range(nb_col):
        print(i, j, array_2d[i, j])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0 0 1
0 1 2
0 2 3
1 0 4
1 1 5
1 2 6
2 0 7
2 1 8
2 2 9


In [6]:
# Mij = max entre (Mi-1,j-1 + score de match ou mismatch) // (Mi-1,j + score de gap) // (Mi,j-1 + score de gap)
for i in range(1, nb_row):
    for j in range(1, nb_col):
        # print(seq2[i-1], seq1[j-1])
        if seq1[i-1] == seq2[j-1]:
            diag_case = matrix_NW[i-1, j-1] + (match_score)
            # print(f"diag_case {matrix_NW[i-1, j-1]} + {match_score} = {diag_case}")
        else:
            diag_case = matrix_NW[i-1, j-1] + (mismatch_score)
            # print(f"diag_case {matrix_NW[i-1, j-1]} + {mismatch_score} = {diag_case}")
            
        left_case = matrix_NW[i, j-1] + (gap_score)
        # print(f"left_case {matrix_NW[i, j-1]} + {gap_score} = {left_case}")
        
        top_case = matrix_NW[i-1, j] + (gap_score)
        # print(f"top_case {matrix_NW[i-1, j]} + {gap_score} = {top_case}")
        
        # print("max ", max(diag_case, left_case, top_case))
        matrix_NW[i, j] = max(diag_case, left_case, top_case)
        # print("\n")
        
matrix_NW

array([[ 0., -1., -2., -3., -4., -5., -6., -7.],
       [-1.,  1.,  0., -1., -2., -3., -4., -5.],
       [-2.,  0.,  0., -1., -2., -3., -2., -3.],
       [-3., -1.,  1.,  0., -1., -1., -2., -1.],
       [-4., -2.,  0.,  2.,  1.,  0., -1., -2.],
       [-5., -3., -1.,  1.,  1.,  0., -1., -2.],
       [-6., -4., -2.,  0.,  0.,  0.,  1.,  0.],
       [-7., -5., -3., -1., -1., -1.,  0.,  0.]])

In [34]:
# Avoir le chemin et score de l'alignement : 
# partir de la case finale et remonter à la case max + récup nom ligne et col

seq1_align="" # en X
seq2_align="" # en Y
score_align = 0

match_score_align = 1
mismatch_indel_score_align = -1

for i in range(nb_row-1, -2, -1):
    for j in range(nb_col-1, -2, -1):
        print( f"diag : {matrix_NW[i-1, j-1]}, top: {matrix_NW[i-1, j]}, left: {matrix_NW[i, j-1]}" ) 
        
        # diag_case, top_vase, left_value
        list_case_value = [matrix_NW[i-1, j-1], matrix_NW[i-1, j], matrix_NW[i, j-1]]
        if max(list_case_value) == list_case_value[0]:
        # if matrix_NW[i-1, j-1] >= max(matrix_NW[i-1, j], matrix_NW[i, j-1]):
            # si diag est sup ou max aux autres val : add lettre à la seq 
            print("diag max", seq1[i-1], seq2[j-1])
            seq1_align += seq1[i-1]
            seq2_align += seq2[j-1]
            i = i-1
            j = j-1
            print(i, j, "\n")
            score_align += matrix_NW[i-1, j-1]
            
        elif max(list_case_value) == list_case_value[1]:
        # elif matrix_NW[i-1, j] > max(matrix_NW[i-1, j-1], matrix_NW[i, j-1]):
            # si top est max : add gap a la seq 
            print("top max", seq1[i-1], seq2[j-1])
            seq1_align += seq1[i-1]
            seq2_align += "_"
            i = i-1
            
            # seq1_align += "_"
            # seq2_align += seq2[j-1]
            # i = i-1
            print(i, j, "\n")
            score_align += matrix_NW[i-1, j]
            
        elif max(list_case_value) == list_case_value[2]:
        # else:
        # elif matrix_NW[i, j-1] > max(matrix_NW[i-1, j-1], matrix_NW[i-1]):
            print("gauche max", seq1[i-1], seq2[j-1])
            # si gauche est max : add gap a la seq 
            seq1_align += "_"
            seq2_align += seq2[j-1]
            j = j-1
            
            # seq1_align += seq1[i-1]
            # seq2_align += "_"
            # j = j-1
            print(i, j, "\n")
            score_align += matrix_NW[i, j-1]
    break
    
print(seq1_align[::-1])
print(seq2_align[::-1])
print(score_align)

diag : 1.0, top: 0.0, left: 0.0
diag max G A
6 6 

diag : 0.0, top: -1.0, left: 0.0
diag max C C
5 5 

diag : 1.0, top: 0.0, left: 1.0
diag max G A
4 4 

diag : 0.0, top: -1.0, left: 2.0
gauche max T T
4 3 

diag : 1.0, top: 0.0, left: 0.0
diag max T T
3 2 

diag : 0.0, top: 0.0, left: -1.0
diag max A A
2 1 

diag : -1.0, top: 1.0, left: -2.0
top max C G
1 1 

diag : -7.0, top: 0.0, left: -5.0
top max G A
0 0 

diag : 0.0, top: 0.0, left: -6.0
diag max G C
-1 -2 

GGCAT_GCG
C__ATTACA
-8.0


In [47]:
seq1_align = ""                                 #The algined sequence (seq1) is going to be appended to this string
seq2_align = ""                                 #The aligned sequence (seq2) is going to be appended to this string
score = 0
i, j = nb_row-1, nb_col-1

match_score_align = 1.0
mismatch_indel_score_align = -1.0

while (i>0 or j>0):
    #Checking if it is a match. If it is a match, then append and jump to the diagonal value directly:
    if seq1[i-1] == seq2[j-1]:
        seq1_align += seq1[i-1]
        seq2_align += seq2[j-1]
        i -= 1
        j -= 1
        score += match_score_align

    #If the sequence don't match:
    else:
        temp_list = [matrix_NW[i-1][j-1], matrix_NW[i-1][j], matrix_NW[i][j-1]]        #Creating a temp_list in order to find the maximum values from top, diagonal and left in order to backtrack

        #If the maximum value is the 0th indexed position, i.e., the diagonal value:
        if max(temp_list) == temp_list[0]:
            seq1_align += seq1[i-1]
            seq2_align += seq2[j-1]
            i -= 1
            j -= 1
            score += match_score_align

        #If the maximum value is the 1st indexed position, i.e., the top value:
        elif max(temp_list) == temp_list[1]:
            seq1_align += seq1[i-1]
            seq2_align += "-"
            i -= 1
            score += mismatch_indel_score_align

        #If the maximum value is the 2nd indexed position, i.e., the left vlaue:
        elif max(temp_list) == temp_list[-1]:
            seq1_align += "-"
            seq2_align += seq2[j-1]
            j-=1
            score += mismatch_indel_score_align

#Reverse the string seq1_align
seq1_align = seq1_align[::-1]
seq2_align = seq2_align[::-1]

print(seq1_align)
print(seq2_align)  
print(score) # le score est la val de la derniere case !!!

GCA-TGCG
G-ATTACA
4.0


- récup des seq (via fasta file ou via pdb)
- NW sur seq deux à deux -> récup score
- UPGMA / embranchement succesif -> obt seq de proche en proche 
- 

In [55]:
import requests
import json
from loguru import logger

In [84]:
def API_PDB_search_based_sequence(pdb_id: str, max_element: int = 10) -> list[str]:
    """This function searches the Protein Data Bank (PDB) database based on a given PDB ID and returns a list of PDB IDs.

    Ressources
    ----------
        https://education.molssi.org/python-scripting-biochemistry/chapters/rcsb_api.html
        https://search.rcsb.org/index.html#return-count

    Parameters
    ----------
        sequence : str
            The amino acid sequence to search for in the PDB database.
        max_element : int, optional
            The maximum number of PDB IDs to retrieve. Defaults to 10.

    Returns
    -------
        list
            A list of PDB IDs corresponding to the sequences found in the PDB database.
    """
    logger.info("Searching PDB IDs based on a given sequence")
    my_query = {
        "query": {
                    "type": "terminal",
                    "label": "full_text",
                    "service": "full_text",
                    "parameters": {
                    "value": pdb_id
                    }
                },
                "return_type": "polymer_entity",
                "request_options": {
                    "paginate": {
                    "start": 0,
                    "rows": 25
                    },
                    "results_content_type": [
                    "experimental"
                    ],
                    "sort": [
                    {
                        "sort_by": "score",
                        "direction": "desc"
                    }
                    ],
                    "scoring_strategy": "combined"
                }
        }

    try:
        my_query = json.dumps(my_query)
        data = requests.get(
            f"https://search.rcsb.org/rcsbsearch/v2/query?json={my_query}"
        )
    except requests.exceptions.HTTPError as http_err:
        logger.error(f"HTTP error occurred: {http_err}")
        return []
    except requests.exceptions.RequestException as req_err:
        logger.error(f"Request error occurred: {req_err}")
        return []

    try:
        results = data.json()
        return results["result_set"][:max_element]
    except requests.exceptions.JSONDecodeError as json_err:
        logger.error(f"JSON decode error occurred: {json_err}")
        return []
    except KeyError as key_err:
        logger.error(f"Key error occurred: {key_err}")
        return []


polymer_id = API_PDB_search_based_sequence("1QJ8")[0]
print(polymer_id)
print("identifier ", polymer_id["identifier"])

# for pdb_id in polymer_id:  
#     print("pdb_id ", pdb_id)

pdb_ID, polymer_entity_id = polymer_id["identifier"].split("_")
dict_pdb_info = {}

try:
    my_query = requests.get(
        f"https://data.rcsb.org/rest/v1/core/polymer_entity/{pdb_ID}/{polymer_entity_id}"
    )
    my_query.raise_for_status()
    results = my_query.json()

    dict_pdb_info["pdb_ID"] = pdb_ID
    dict_pdb_info["polymer_id"] = polymer_entity_id
    # dict_pdb_info["names"] = get_macromolecular_names_bis(results)
    # dict_pdb_info["organism"] = get_organism_names(results)
    print(dict_pdb_info)

except requests.exceptions.RequestException as err:
    print(f"Error: {err}")
    print(dict_pdb_info)





# print(API_PDB_search_based_sequence("1QJ8"))

2024-09-09 14:58:47.958 | INFO     | __main__:API_PDB_search_based_sequence:21 - Searching PDB IDs based on a given sequence


{'identifier': '1QJ8_1', 'score': 1.0}
identifier  1QJ8_1


NameError: name 'get_macromolecular_names_bis' is not defined

In [87]:
from Bio import SeqIO


In [104]:
records = list(SeqIO.parse("../1QJ8.fasta", "fasta"))[0]

print(records.seq)
print(records.name)
# for seq in records:
#     print(str(seq.seq))
#     print(seq.name)

ATSTVTGGYAQSDAQGQMNKMGGFNLKYRYEEDNSPLGVIGSFTYTEKSRTASSGDYNKNQYYGITAGPAYRINDWASIYGVVGVGYGKFQTTEYPTYKNDTSDYGFSYGAGLQFNPMENVALDFSYEQSRIRSVDVGTWIAGVGYRF
1QJ8_1|Chain


In [105]:
import sys

In [106]:
i = 3
while i > 0:
    for line in sys.stdin:
        print(line)
    

KeyboardInterrupt: 